### ISSUE TITLE
Broken build on merged PR #9 

### ISSUE THREAD

**Issue by kmuehlbauer** [conda-forge/python-eccodes-feedstock#12]
The PR #9 pinned boost correctly to 1.62. The build is failing, because the 'eccodes' dependency was pinned to 1.61 until https://github.com/conda-forge/eccodes-feedstock/pull/19. AFAIK we just need to restart the CI's when the 'eccodes' packages are available at anaconda, to get in line again. 

@jjhelmus Thanks again for finding and fixing.

**Comment by kmuehlbauer** [comment]
CircleCi was already successful. So the linux builds are now available on anaconda. `eccodes` is still waiting in the queue on Travis-CI.

**Comment by kmuehlbauer** [comment]
Everything is built and uploaded. Closing...

**Comment by kynan** [comment]
That was my bad, I would have needed to wait until all the CI runs for eccodes had finished before merging in #9. Thanks for sorting @kmuehlbauer!

**Comment by kmuehlbauer** [comment]
No worries 👍
