### ISSUE TITLE
python-eccodes 2.10.0 in beta?

### ISSUE THREAD

**Issue by bjlittle** [conda-forge/python-eccodes-feedstock#43]
Just asking the obvious question here... so put me right or shoot me down, but isn't this `python-eccodes` version a beta release? From the ECMWF, see [here](https://confluence.ecmwf.int/display/SUP/2018/12/04/December+2018+software+release) and [here](https://confluence.ecmwf.int//display/ECC/ecCodes+version+2.10.0+released).

If this is beta, then shouldn't the `conda-forge` version reflect this status to the Python community for clarity?

**Comment by kmuehlbauer** [comment]
According to semver this is no beta :grin: The question is, how should this be reflected here?

**Comment by kmuehlbauer** [comment]
@bjlittle That's what I was writing. The released version is `2.10.0` and not `2.10.0-beta` according to ECMWF. 

I have no strong feelings either way, so what is the cf way of handling this, @ocefpaf?

**Comment by ocefpaf** [comment]
> @bjlittle That's what I was writing. The released version is `2.10.0` and not `2.10.0-beta` according to ECMWF.

I agree with @kmuehlbauer, the info is not in the version so it is not semver. (If we have to dig that kind of info from every release web page/email/announcement conda-forge would grind to a halt!)

> I have no strong feelings either way, so what is the cf way of handling this, @ocefpaf?

We can fix that if the maintainers here up to it but I also don't have strong feelings about it. What ever is easier is fine by me.

**Comment by bjlittle** [comment]
Thanks everyone for the discussion and the common sense clarification - it's really helpful!

I'm more than happy to close this issue, cheers :smile:
