### ISSUE TITLE
version madness

### ISSUE THREAD

**Issue by beckermr** [conda-forge/python-eccodes-feedstock#49]
So apparently the upstream package split out the python package (a good thing) but decided to reset the version number. So to update this feedstock for `eccodes >=2.13.0`, the new version would be [0.9.2](https://pypi.org/project/eccodes-python/). The current version of this feedstock is based on the upstream `eccodes` version of `2.12.*`. 

@conda-forge/python-eccodes How should we proceed here?

**Comment by kmuehlbauer** [comment]
Good question! The PyPI Package is Python3 only. So my suggestion would be to drop Python2 support for this feedstock now. 

As the new build would be for ecCodes v2.13.0 we might have to mark older py3 packages as broken then. 

Another thing is, that the new bindings can be [compiled](https://pypi.org/project/eccodes-python/). @ocefpaf any idea how to incorporate this?

**Comment by kmuehlbauer** [comment]
> This is not needed. Conda will resolve the version dependence of the individual build on ecCodes properly.

Will `$ conda install python-eccodes` install the 0.9.2 version (if it's build) or the 2.12.3 which is latest?

**Comment by kmuehlbauer** [comment]
Ah, I see, in #48 the package is just pulled from PyPI and installed alongside the eccodes build. But that means we will build eccodes twice. In the `eccodes-feedstock` and here.

And, we would have a conda-forge version naming contradicting the `python-eccodes` PyPI version. Seems not easy to sort out properly.

**Comment by kmuehlbauer** [comment]
> The question I thought I was answering was "Will conda get confused and try and install python-eccodes 0.9.2 with eccodes 2.12.3?" The answer to this question is no as long as the python-eccodes recipe depends on the eccodes one via the `meta.yaml`.

IIUC, we can use the new version (0.9.2) in this feedstock and depend on eccodes 2.13.0 via `meta.yaml` and conda will take care of it. But with the consequence of dropping python2 support, right?
