### ISSUE TITLE
Possible Windows support

### ISSUE THREAD

**Issue by djhoese** [conda-forge/python-eccodes-feedstock#52]
What is the current state of Windows support for this package and building it on conda-forge? Was it ever attempted? I see on the PyPI page that it says the package is untested on Windows. Any gotchas or other difficulties I would run in to if I tried to add it?

Reason: I have a GUI application that currently depends on pygrib which is not Windows compatible so the conda package for my GUI application is not noarch because of this (even though it is pure python). I would like to switch to eccodes-python but if we (meaning conda-forge) can't get it built for windows then I'll have the same issue.

Side question: Why is the conda package not called `eccodes-python` like the PyPI package?

**Comment by kmuehlbauer** [comment]
> Side question: Why is the conda package not called `eccodes-python` like the PyPI package?

Because, the PyPI packages was created first this year, and this feedstock exists for quite some time. Never thought, that there might be a dedicated PyPI package one day. Further info on the naming issue: https://github.com/conda-forge/python-eccodes-feedstock/issues/49 and https://github.com/conda-forge/eccodes-feedstock/pull/88. Not sure how to break out without breaking things for users.

No information so far on the windows issue, sorry @djhoese. But @dtip might know something.

**Comment by dtip** [comment]
Hi @djhoese - I can't remember for the life of me why ECMWF didn't want Windows support for the ecCodes Python interface. I added support for ecCodes, Magics, magics-python, and CodesUI. @StephanSiemen should know the answer to your question.

If we're lucky we can get windows support here for free. I'll give it a go and see what happens.

**Comment by dtip** [comment]
PR here: https://github.com/conda-forge/python-eccodes-feedstock/pull/53

**Comment by ColinDuff** [comment]
hi, i tried to download the windows python-eccodes from conda-forge but i get the following error:-

UnsatisfiableError: The following specifications were found to be in conflict:
  - defaults/win-64::wincertstore==0.2=py37_0
  - python-eccodes

i am running python 3.7 - any ideas

**Comment by kynan** [comment]
@ColinDuff [wincertstore is not available for Python 3.7 in the default channel](https://anaconda.org/anaconda/wincertstore/files), but it is on [conda-forge](https://anaconda.org/conda-forge/wincertstore/files).

**Comment by ColinDuff** [comment]
hi, so i reinstalled the wincertstore fro conda-forge but now i get 
UnsatisfiableError: The following specifications were found to be in conflict:
  - conda-forge/win-64::win_inet_pton==1.1.0=py37_0
  - python-eccodes

thanks for your help

**Comment by meso2** [comment]
@djhoese @dtip  I wonder if anyone here has already got eccodes python working under Python 3.7.1 and Windows 10? Many thanks.

**Comment by dtip** [comment]
@meso2 I haven't tried, but it should work fine in a clean python environment. What problems are you seeing?

**Comment by meso2** [comment]
@dtip Thanks. 

Here is the problem I have.

This is what I've done under Windows 10 and Python 3.7.1:

(1) Download python-eccodes-2020.03.0-py37hbc2f12b_2.tar.bz2 from https://anaconda.org/conda-forge/python-eccodes/files and install eccodes-python by using 'conda install python-eccodes-2020.03.0-py37hbc2f12b_2.tar.bz2'

(2)Download eccodes 2.17.0 eccodes-2.17.0-h37af81a_0.tar.bz2 from https://anaconda.org/conda-forge/eccodes/files and installInstall eccodes by using 'conda install eccodes-2.17.0-h37af81a_0.tar.bz2'

 (3) After running 'python -m eccodes selfcheck', it shows the following messages:

Found: ecCodes v2.17.0.

Your system is ready.

(4) Launch Python 3.7.1 and import eccodes, all good, 

(5) When I ran the following small piece of code 'python test.py', nothing happened (no error message, no results) but it exited. I guess the script crashed. The line in the script which caused the crash is eccodes.codes_get(gid, 'dataDate').

========================================================
import eccodes

import datetime

fn = '../data/ecsf/ecsf200507.grb'

f = open(fn)

gid = eccodes.codes_grib_new_from_file(f)

if gid is None:   exit(0)

try:

   initial_time = datetime.datetime.strptime(str(eccodes.codes_get(gid, 'dataDate')),'%Y%m%d')

   print (initial_time)

except eccodes.CodesInternalError as err:

   print ('Error with key="%s" : %s' % (key, err.msg))

======================
Any ideas? Thanks.

**Comment by dtip** [comment]
Could you try install python-eccodes directly from conda-forge:

```
conda install -c conda-forge python-eccodes
```

You shouldn't have to mess with tarballs when using conda!

**Comment by xylar** [comment]
As far as I can tell, Windows is now supported.  If there are ongoing problems 3 years later, it would be best to open a new issue.

**Comment by shahramn** [comment]
Also try calling the "open" function with the BINARY mode
e.g.,
`f = open(mygrib, "rb")`
