### ISSUE TITLE
Linking issue with eccodes 2.19.1

### ISSUE THREAD

**Issue by djhoese** [conda-forge/python-eccodes-feedstock#69]
- [ ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

See https://github.com/conda-forge/eccodes-feedstock/issues/120 for all the details.

Something has changed in the conda-forge ecosystem in the last 24 hours that is causing some solvers to choose eccodes 2.19.1 when installing python-eccodes. Before that eccodes 2.20.0 was being used and works fine. However, with 2.19.1 I get:

```
>       from ._bindings import ffi, lib
E       ImportError: /usr/share/miniconda3/envs/test-environment/lib/python3.8/site-packages/gribapi/_bindings.cpython-38-x86_64-linux-gnu.so: undefined symbol: codes_bufr_key_is_header

/usr/share/miniconda3/envs/test-environment/lib/python3.8/site-packages/gribapi/bindings.py:29: ImportError
```

Forcing the eccodes version to 2.20.0 or above seems to have fixed things.

**Comment by kynan** [comment]
First guess: this may be related to the `pip` dependency resolver [introduced in `pip` 20.3](https://blog.python.org/2020/11/pip-20-3-release-new-resolver.html).

**Comment by ocefpaf** [comment]
> First guess: this may be related to the `pip` dependency resolver [introduced in `pip` 20.3](https://blog.python.org/2020/11/pip-20-3-release-new-resolver.html).

It should not influence on our package metadata. We should probably [change this](https://github.com/conda-forge/python-eccodes-feedstock/blob/master/recipe/meta.yaml#L30) from `>=` to `==`

**Comment by alexamici** [comment]
> It should not influence on our package metadata. We should probably [change this](https://github.com/conda-forge/python-eccodes-feedstock/blob/master/recipe/meta.yaml#L30) from `>=` to `==`.

The correct solution in this case is to bump `eccodes_version`, but I don't find when `codes_bufr_key_is_header` has been introduced. Should be `2.20.0` or `2.21.0`.

**Comment by alexamici** [comment]
This combination crashes with `Symbol not found: _codes_bufr_key_is_header`:
```$ conda env export --no-build | grep eccodes
  - eccodes=2.19.0
  - python-eccodes=2021.03.0```

Bumpiing to 2.20.0 doesn't crash, but raises a warning:
```$ conda env export --no-build | grep eccodes
  - eccodes=2.20.0
  - python-eccodes=2021.03.0
$  cfgrib selfcheck
Warning: ecCodes 2.21.0 or higher is recommended. You are running version 2.20.0
Found: ecCodes v2.20.0.
Your system is ready.
```
