### ISSUE TITLE
Can we change python-eccodes to noarch?

### ISSUE THREAD

**Issue by iainrussell** [conda-forge/python-eccodes-feedstock#80]
### Comment:

This came up because someone could not install cfgrib, which depends on python-eccodes, on aarch64 platform (https://github.com/ecmwf/cfgrib/issues/302).
I'm not sure if there's a good reason why python-eccodes is not 'noarch', but rather there is a build for each architecture (https://anaconda.org/conda-forge/python-eccodes). It is very similar to metview-python (which is noarch), in that it uses cffi to connect to a binary library. Perhaps the difference is that python-eccodes has the eccodes binaries as a dependency? If that means that python-eccodes cannot be noarch, then we should add aarch64 to its platforms, but my preference is noarch if there's no good reason not to do that. Then python-eccodes will not care about particular platforms, but the eccodes package itself can take care of deciding which particular platforms it supports. Thoughts?

**Comment by xylar** [comment]
Yes, I'm afraid that python-eccodes compiles C code as part of its installation so there's not a way to have a `noarch: python` build.  I would assume the reason that aarch64 and ppc64le aren't available is likely to do with one or more dependencies not having been built for those architectures but I could be wrong about that.
